export const AUDIT_CATEGORIES = Object.freeze({
  ACCOUNT: "account",
  STUDENT: "student",
  ROOM: "room",
  COMPLAINT: "complaint",
  LEAVE: "leave",
  GATE: "gate",
  MESS: "mess",
  NOTICE: "notice",
});

export const AUDIT_ACTIONS = Object.freeze({
  STAFF_INVITATION_CREATED: "staff.invitation.created",
  ACCOUNT_STATUS_CHANGED: "account.status.changed",
  STUDENT_APPROVAL_CREATED: "student.approval.created",
  STUDENT_APPROVALS_IMPORTED: "student.approvals.imported",
  STUDENT_APPROVAL_REVOKED: "student.approval.revoked",
  STUDENT_APPROVAL_REINSTATED: "student.approval.reinstated",
  STUDENT_ACTIVATION_REISSUED: "student.activation.reissued",
  ROOM_ALLOCATION_CREATED: "room.allocation.created",
  ROOM_ALLOCATION_VACATED: "room.allocation.vacated",
  COMPLAINT_CREATED: "complaint.created",
  COMPLAINT_ASSIGNED: "complaint.assigned",
  COMPLAINT_REASSIGNED: "complaint.reassigned",
  COMPLAINT_ATTACHMENT_ADDED: "complaint.attachment.added",
  COMPLAINT_ATTACHMENT_DELETED: "complaint.attachment.deleted",
  COMPLAINT_WORK_STARTED: "complaint.work.started",
  COMPLAINT_SLA_BREACHED: "complaint.sla.breached",
  COMPLAINT_RESOLVED: "complaint.resolved",
  COMPLAINT_REOPENED: "complaint.reopened",
  COMPLAINT_CLOSED: "complaint.closed",
  LEAVE_REQUEST_SUBMITTED: "leave.request.submitted",
  LEAVE_REQUEST_APPROVED: "leave.request.approved",
  LEAVE_REQUEST_REJECTED: "leave.request.rejected",
  GATE_PASS_ISSUED: "gate-pass.issued",
});

export const AUDIT_RESOURCE_TYPES = Object.freeze({
  STAFF_INVITATION: "staff_invitation",
  USER_ACCOUNT: "user_account",
  APPROVED_STUDENT: "approved_student",
  STUDENT_IMPORT: "student_import",
  ROOM_ALLOCATION: "room_allocation",
  COMPLAINT: "complaint",
  COMPLAINT_ASSIGNMENT: "complaint_assignment",
  COMPLAINT_ATTACHMENT: "complaint_attachment",
  LEAVE_REQUEST: "leave_request",
  GATE_PASS: "gate_pass",
});
